spring.application.name=gateway

spring.jpa.show-sql=true

# =========================================================
# Eureka
# =========================================================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://service-registry:8081/eureka/}
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.prefer-ip-address=true

# =========================================================
# Server
# =========================================================
server.port=8082

# =========================================================
# SpringDoc
# =========================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true

# =========================================================
# LOGS
# =========================================================
logging.level.org.springframework.security=TRACE
logging.level.io.github.resilience4j=INFO
logging.level.org.springframework.cloud.client.circuitbreaker=INFO
logging.level.feign=INFO
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.reactor.netty.http.client=DEBUG

# =========================================================
# ACTUATOR / HEALTH
# =========================================================
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always

jwt.secret=${ATCARE_JWT_SECRET}
jwt.issuer=${ATCARE_JWT_ISSUER}

spring.main.web-application-type=reactive

# Discovery Locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*