INSERT INTO at_especialidade (
    id,
    at_id,
    especialidade_id,
    criado_por,
    criado_em,
    atualizado_por,
    atualizado_em,
    ativo
) VALUES
(1,1,1,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(2,2,2,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(3,3,3,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(4,4,4,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(5,5,5,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(6,6,6,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(7,7,7,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(8,8,8,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(9,9,9,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(10,10,10,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE);

