INSERT INTO local_atendimento (
    id,
    at_id,
    endereco_id,
    atendimento_domiciliar,
    atendimento_online,
    criado_por,
    criado_em,
    atualizado_por,
    atualizado_em,
    ativo
) VALUES
(1,1,1,TRUE,TRUE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(2,2,2,TRUE,FALSE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(3,3,3,FALSE,TRUE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(4,4,4,TRUE,TRUE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(5,5,5,TRUE,FALSE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(6,6,6,FALSE,TRUE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(7,7,7,TRUE,TRUE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(8,8,8,TRUE,FALSE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(9,9,9,FALSE,TRUE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE),
(10,10,10,TRUE,TRUE,1,CURRENT_TIMESTAMP(6),NULL,NULL,TRUE);

